In [1]:
import pandas as pd

In [5]:
# Read in CSV 
tourney_team_df = pd.read_csv('Resources/Tournament Team Data.csv')
tourney_team_df

,YEAR,SEED,TEAM,TEAM ROUND,CURRENT ROUND,KENPOM ADJUSTED EFFICIENCY,KENPOM ADJUSTED OFFENSE,KENPOM ADJUSTED DEFENSE,KENPOM ADJUSTED TEMPO,BARTTORVIK ADJUSTED EFFICIENCY,...,OP D REB %,BLOCKED %,TURNOVER % DEFENSE,WINS ABOVE BUBBLE,WIN %,POINTS PER POSSESSION OFFENSE,POINTS PER POSSESSION DEFENSE,SCORE,ID,TEAM.1
0,2022,1,Gonzaga,16,64,33.0000,121.800,88.8000,72.5000,31.800,...,71.0,6.6,17.0,6.7,89.660000,1.190,0.885,93,1,Gonzaga
1,2022,16,Georgia St.,64,64,1.8000,101.500,99.7000,67.1000,1.400,...,67.2,8.9,22.7,-5.2,60.000000,0.993,0.978,72,2,Georgia St.
2,2022,8,Boise St.,64,64,16.4000,108.400,92.0000,64.6000,15.200,...,69.4,8.9,20.1,3.5,78.790000,1.038,0.928,53,3,Boise St.
3,2022,9,Memphis,32,64,16.2000,110.400,94.1000,70.3000,17.500,...,62.5,9.1,20.9,1.4,67.740000,1.056,0.957,64,4,Memphis
4,2022,5,Connecticut,64,64,19.3000,113.900,94.6000,64.9000,18.600,...,62.0,8.3,18.0,3.2,71.880000,1.099,0.953,63,5,Connecticut
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1903,2023,5,Miami FL,0,0,15.9173,117.103,101.1850,67.7143,14.973,...,68.0,8.1,18.5,1.5,76.190476,1.132,1.013,0,0,Miami FL
1904,2023,1,Houston,0,0,30.1797,117.454,87.2747,62.9998,29.814,...,62.0,7.2,22.9,4.7,90.909091,1.170,0.852,0,0,Houston
1905,2023,5,Rutgers,0,0,19.9569,106.343,86.3864,65.2614,18.955,...,66.0,9.3,23.2,0.5,70.000000,1.039,0.847,0,0,Rutgers
1906,2023,1,Tennessee,0,0,29.5396,112.221,82.6819,66.9930,28.991,...,62.0,8.4,24.6,3.3,85.714286,1.097,0.804,0,0,Tennessee
1907,2023,5,Connecticut,0,0,24.8013,116.651,91.8497,67.3417,23.650,...,64.0,8.6,20.6,2.0,72.727273,1.132,0.919,0,0,Connecticut